@startuml "goarchlint"
skinparam componentStyle rectangle
[/cmd/goarchlint] --> [/linter]
[/cmd/goarchlint] --> [/parser]
[/cmd/goarchlint] --> [/render]
[/linter] --> [/model]
[/parser] --> [/model]
[/render] --> [/model]
@enduml