package render

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/gbh007/goarchlint/model"
)

type Format byte

const (
	FormatNone Format = iota
	FormatMermaid
	FormatPlantUML
)

type Render struct {
	OnlyInner        bool
	PreferInnerNames bool
	MarkdownMode     bool
	Format           Format
	BasePath         string
	SchemeFileFormat Format
}

func (r Render) getPackagePath(p model.Package) string {
	s := p.RelativePath
	if r.PreferInnerNames {
		s = p.InnerPath
	}

	s, f := path.Split(s)
	s = strings.Trim(s, "/")

	if f == "" && p.IsMain { // FIXME: избавится от этого костыля
		f = "main"
	}

	return path.Join(s, f+".md")
}

func (r Render) getImportPath(p model.Import) string {
	s := p.RelativePath
	if r.PreferInnerNames {
		s = p.InnerPath
	}

	s, f := path.Split(s)
	s = strings.Trim(s, "/")

	return path.Join(s, f+".md")
}

func (Render) resolvePath(current, target string) string {
	s, err := filepath.Rel(current, target)
	if err != nil {
		panic(err)
	}

	s = strings.TrimPrefix(s, "../") // FIXME: избавится от этого костыля

	return s
}

func (Render) mdLink(name, uri string) string {
	if path.Base(uri) == ".md" { // FIXME: избавится от этого костыля
		return name
	}

	return fmt.Sprintf("[%s](%s)", name, uri)
}

func (Render) checkAndCreateDir(dirPath string) error {
	info, err := os.Stat(dirPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("os stat: %w", err)
	}

	if info != nil && !info.IsDir() {
		return errors.New("dir path is not dir")
	}

	err = os.MkdirAll(dirPath, os.ModeDir|os.ModePerm)
	if err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}

	return nil
}

func (Render) renderFileFooter(w io.Writer) error {
	_, err := io.WriteString(w, "\n---\n\n> Generated by [goArchLint](https://github.com/gbh007/goarchlint)\n")
	if err != nil {
		return err
	}

	return nil
}
